version: 2.1
orbs:
   aws-cli: circleci/aws-cli@3.1
   serverless-framework: circleci/serverless-framework@2.0
jobs:
   build-and-deploy:
     executor: serverless-framework/default
     steps:
       - setup_remote_docker:
           version: 20.10.2
       - checkout
       - aws-cli/setup
       - serverless-framework/setup
       - run: sls deploy 
workflows:
  pacetest:
    jobs:
      - build-and-deploy