version: 2.1
orbs:
  python: circleci/python@1.5.0
jobs:
  build-and-deploy:
    docker:
      - image: cimg/python:3.10.2
   steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          # command: pytest
          command: sudo npm i -g serverless npm@latest
      - run:
          command: npm install
      - run:
          command: ./.circleci/install-credentials.sh
      - run:
          command: sls deploy

workflows:
  pacetest:
    jobs:
      - build-and-deploy:
        context: pacetestProject
        filter:
          branches:
            only:
              - test-CI


# version: 2.1
# orbs:
#   python: circleci/python@1.5.0
# jobs:
#   build-and-deploy:
#     executor: serverless/default
#     steps:
#        - checkout
#        - aws-cli/setup
#        - serverless/setup
#        - run: sls deploy 
# workflows:
#   pacetest:
#     jobs:
#       - build-and-deploy