version: 2.1
orbs:
   aws-cli: circleci/aws-cli@1.0
   serverless: circleci/serverless-framework@1.0
jobs:
   build-and-deploy:
     executor: serverless/default
     steps:
       - checkout
       - aws-cli/setup
       - serverless/setup
       - run: sls deploy 
workflows:
  pacetest:
    jobs:
      - build-and-deploy